# map recognized instruments to standard ids
instrument_map = {
    'voice' : 'voice',
    'piano' : 'piano',
    'cemba' : 'piano',
    'Violoncello' : 'cello',
    'cello' : 'cello',
    'Viola' : 'viola',
    'viola' : 'viola',
    'Violino II' : 'violin',
    'Violino I' : 'violin',
    'Violino' : 'violin',
    'violin' : 'violin',
    'violn' : 'violin',
    'Bass' : 'bass',
    'Bassus' : 'bass',
    'Baritonans' : 'bass',
    'Bariton' : 'bass',
    'Barriphanos' : 'bass',
    'Baryphonus' : 'bass',
    'Contratenor Basis' : 'bass',
    'Contratenor Bassus' : 'bass',
    'Contrabassus' : 'bass',
    'Soprano' : 'soprano',
    'Superius' : 'soprano',
    '[Superius]' : 'soprano',
    'Discantus' : 'soprano',
    'Discant' : 'soprano',
    'Cantus' : 'soprano',
    'Secunda vox' : 'soprano',
    'Secundus puer' : 'soprano',
    'Alto' : 'alto',
    'Altus' : 'alto',
    '[Altus]' : 'alto',
    'Tenor' : 'tenor',
    'Tenor I' : 'tenor',
    'Tenor II' : 'tenor',
    'Contratenor' : 'countertenor',
    'Contra' : 'countertenor',
    'Contratenor Altus' : 'countertenor',
    'Contraltus' : 'countertenor',
    'Vagans' : 'quintus',
    'Quintus' : 'quintus',
    'Sextus' : 'sextus',

    # I don't really know what these are but we'll assign them their own id
    'unknown' : 'unknown',
    'Faulx bourdon' : 'fauxbourdon',
    '[Dux]' : 'dux',
    '[Comes]' : 'comes',
    'Bell' : 'bell',
    'Baripsaltes' : 'baricanor',
    'Baricanor' : 'baricanor',
    'Canon Royal' : 'canonroyal',
    'Inferior' : 'inferior',
    'Inferior vox' : 'inferior',
    'Superior' : 'superior',
    'Superior vox' : 'superior',
}

